# Build settings
markdown:            kramdown
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-loading-lazy, jekyll-katex]
title:		           'The Computation Side of Things'
author:              'Mohamed Rezk'
future:               true
