# title:		           'The Computation Side of Things'
title:               'Mohamed El Shorbagy'
author:              'Mohamed Rezk'
markdown:            kramdown
permalink:           /:title

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-katex
